# import os
# from dotenv import load_dotenv

# load_dotenv()

# GEOCODING_BASE_URL = os.getenv("GEOCODING_BASE_URL")
# ROUTING_BASE_URL = os.getenv("ROUTING_BASE_URL")

# SWABI_API_BASE_URL = os.getenv("SWABI_API_BASE_URL")
# BOOKING_LIST_ENDPOINT = os.getenv("BOOKING_LIST_ENDPOINT")
# BOOKING_DETAIL_ENDPOINT = os.getenv("BOOKING_DETAIL_ENDPOINT")

# DEFAULT_VENDOR_ID = int(os.getenv("DEFAULT_VENDOR_ID", 1))
# BOOKING_STATUS = os.getenv("BOOKING_STATUS", "BOOKED")

# DATABASE_URL = os.getenv("DATABASE_URL")

# PICKUP_BUFFER_MINUTES = int(os.getenv("PICKUP_BUFFER_MINUTES", 20))
# SCHEDULER_INTERVAL_MINUTES = int(os.getenv("SCHEDULER_INTERVAL_MINUTES", 60))




import os
from dotenv import load_dotenv

load_dotenv()

GEOCODING_BASE_URL = os.getenv("GEOCODING_BASE_URL")
ROUTING_BASE_URL = os.getenv("ROUTING_BASE_URL")

BOOKING_LIST_ENDPOINT = os.getenv("BOOKING_LIST_ENDPOINT")
BOOKING_DETAIL_ENDPOINT = os.getenv("BOOKING_DETAIL_ENDPOINT")
DEFAULT_VENDOR_ID = int(os.getenv("DEFAULT_VENDOR_ID", 1))
BOOKING_STATUS = os.getenv("BOOKING_STATUS", "BOOKED")

PICKUP_BUFFER_MINUTES = int(os.getenv("PICKUP_BUFFER_MINUTES", 20))
SCHEDULER_INTERVAL_MINUTES = int(os.getenv("SCHEDULER_INTERVAL_MINUTES", 60))

DATABASE_URL = os.getenv("DATABASE_URL")
